# -*- coding: utf-8 -*-
"""Video Frame Extractor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPqrdv0bVvI-G9OMVqTQxobILPCF0Jgd
"""

import cv2
import os

def extract_frames(video_path, output_folder, interval=0.2):
    # interval=0.2 Represents a cut every 0.2 seconds.

    # create output folder
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    # read the video
    cap = cv2.VideoCapture(video_path)
    # read video's fps
    fps = cap.get(cv2.CAP_PROP_FPS)
    # Find the intervals where the cuts need to fall according to the desired time intervals.
    frame_interval = int(fps * interval)

    frame_count = 0
    saved_count = 0

    while True:
        # Read frame from video
        ret, frame = cap.read()
        # If there is no frame to read
        if not ret:
            break
        # If it is the desired interval, save
        if frame_count % frame_interval == 0:
            output_file = os.path.join(output_folder, f"frame_{saved_count:04d}.jpg")
            cv2.imwrite(output_file, frame)
            saved_count += 1
        frame_count += 1
    cap.release()
    print(f"Extracted {saved_count} image.")


extract_frames('./model generated by sudoai.mp4', 'output_frames', interval=0.2)